config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :recipes

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
  end

  def create
    render plain: params[:recipe].inspect
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rconverter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_with scope: :recipe, url: recipes_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Baking Pan Conversion Tool</h1>
<h3>A simple tool for adjusting recipes to work with different types and sizes of pans.</h3>
<p style="font-family: Arial, Lucida Sans Unicode, Verdana, sans-serif">The recipe calls for the following pans:<br /><p>
<p>I want to bake with the following pans:<br /><p>
<p>The ingredient list of the recipe is:<br /><p>